In [1]:
import numpy as np
from scipy.optimize import linear_sum_assignment
c = [[3,8,6,9,5], [7,5,12,9,19], [7,10,9,10,6], [4,6,2,12,8], [9,9,6,15,11]]
c = np.array(c)
print(c)
name_id, work_id = linear_sum_assignment(c)
print(name_id)
print(work_id)
print(c[name_id,work_id ].sum())

[[ 3  8  6  9  5]
 [ 7  5 12  9 19]
 [ 7 10  9 10  6]
 [ 4  6  2 12  8]
 [ 9  9  6 15 11]]
[0 1 2 3 4]
[0 3 4 2 1]
29
