In [3]:
import numpy as np

# 归一化后的方案——准则矩阵
A = np.mat('0.27 0.37 0.31 0.17; 0.14 0.22 0.09 0.02; 0.13 0.09 0.12 0.51; 0.13 0.15 0.31 0.19; 0.33 0.17 0.16 0.10')
print("方案——准则矩阵：", A)

# 平均随机一致性指标
RI = [0,0,0.52,0.89,1.12,1.26,1.36,1.41,1.46,1.49]
# 准则——判断矩阵
B = np.array([[1, 2, 3, 5], [1/2, 1, 1/2, 2], [1/3, 2, 1, 2], [1/5, 1/2, 1/2, 1]])
# print(B)
n = 4
# 特征值，特征向量
value, vector = np.linalg.eig(B)
# 最大特征值
lmd = max(value)
# 一致性比例
CR =  (lmd-n) / (n-1)
# 一致性检验
if CR < 0.1 :
    print("通过了一致性检验")
else :
    print("未通过一致性检验")
    exit(-1)

# 按列归一化   
sumval = 0
val = []
for i in range(n):
    for j in range(n):
        sumval += B[j][i]
    val.append(sumval)
    sumval = 0
    
# print(val)
deduce1Val = []
for i in range(n):
    for j in range(n):
        deduce1Val.append(B[i][j] / val[j])

def chunk_list(lst, chunk_size):
    return [lst[i:i + chunk_size] for i in range(0, len(lst), chunk_size)]

finalB =  chunk_list(deduce1Val, 4)       
# print(finalB)

# 权重矩阵
weightMat = []
for i in range(n):
    weightMat.append(sum(finalB[i][0:]) / n)
    
# print(weightMat)
w = np.array(weightMat)
print("权重矩阵：", w)

# 得分矩阵
points = np.dot(A, w)
# print(points)
name = ['老番茄','何同学','木鱼水心','凉风','罗翔']
print("最终得分：", {name[i]:points[0,i] for i in range(5)})

方案——准则矩阵： [[0.27 0.37 0.31 0.17]
 [0.14 0.22 0.09 0.02]
 [0.13 0.09 0.12 0.51]
 [0.13 0.15 0.31 0.19]
 [0.33 0.17 0.16 0.1 ]]
通过了一致性检验
权重矩阵： [0.48885991 0.18192996 0.2318927  0.09731744]
最终得分： {'老番茄': 0.2877369597615499, '何同学': 0.13128166915052158, '木鱼水心': 0.15738450074515647, '凉风': 0.18121833084947836, '罗翔': 0.23908643815201192}
